#!/bin/bash

export VIDEOS=/mnt/archive/BYKHUN/phystechtv

function play {
    echo `date "+%Y-%m-%d %H:%M:%S"`: "$1" >> play.log;

    ffmpeg -re -i "$1" \
    -i phystech.tv.png -filter_complex "overlay=main_w-overlay_w-0:0" \
    -vcodec libx264 -vprofile baseline -g 30 \
    -s 1920x1080 \
    -acodec aac -strict -2 \
    -f flv rtmp://phystech.tv/live/stream
}

export -f play

while true; do
  find $VIDEOS -name "*.*" | shuf | xargs -I $ sh -c 'play "$";'
done

